### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by davidbludlow** [mudoo/quill-resize-module#1]
I love what you are trying to accomplish in this fork, but I can't use it, because every time I click on an image I get
```
Uncaught TypeError: Cannot read property 'style' of undefined
    at Toolbar.js:90
    at Array.forEach (<anonymous>)
    at Toolbar._addToolbarButtons (Toolbar.js:67)
    at Toolbar.onCreate (Toolbar.js:29)
    at QuillResize.js:82
    at Array.forEach (<anonymous>)
    at QuillResize.initializeModules (QuillResize.js:81)
    at QuillResize.show (QuillResize.js:176)
    at QuillResize.judgeShow (QuillResize.js:158)
    at QuillResize.handleClick (QuillResize.js:120)
```
This only happens with medium and large pictures. When I use small pictures, then nothing happens. Nothing useful or harmful happens when I try to resize a small picture, but I am not as worried about that as I am worried about the exception. 

After the exception, there is a little gray box in the top left corner of the picture, as shown in this screenshot
![image](https://user-images.githubusercontent.com/5985136/77219746-77aca380-6b06-11ea-8873-2c580b7f6e5c.png)

Here is the offending code:
![image](https://user-images.githubusercontent.com/5985136/77219687-079e1d80-6b06-11ea-8d13-355b91648113.png)
`button.children` is an empty array

**Comment by mudoo** [comment]
I think it is svg problem, svg can not work with path. you must insert svg content to the button.
Try to use `raw-loader`.
```
{
  test: /\.svg$/,
  use: 'raw-loader'
}
```

**Comment by GuillaumeGorret** [comment]
Sorry to comment this closed issue. But where do you put the code you mentionned ?
`{
  test: /\.svg$/,
  use: 'raw-loader'
}`

**Comment by mudoo** [comment]
@GuillaumeGorret webpack.config.js
https://www.npmjs.com/package/raw-loader

**Comment by kirqe** [comment]
Using it with rails, I added 

```
environment.loaders.append(
  'svg', 
  { test: /\.svg$/,  use: 'raw-loader' }
)
```

But it doesn't seem to help  button.children[0] is undefined
https://github.com/mudoo/quill-resize-module/issues/5

**Comment by kirqe** [comment]
Apparently raw-loader doesn't work. This is the solution https://github.com/quilljs/webpack-example/issues/3#issuecomment-658294912
