### ISSUE TITLE
demo/index.html is busted

### ISSUE THREAD

**Issue by davidbludlow** [mudoo/quill-resize-module#2]
I tried looking at demo/index.html for guidance, but that is busted. It looks like 
![image](https://user-images.githubusercontent.com/5985136/77218742-94dc7480-6afc-11ea-8ec3-774723e6dc65.png) when I open it up in a browser

**Comment by mudoo** [comment]
Looks like you run index.html with local. Try to run `npm run dev` in the terminal.
