### ISSUE TITLE
Not working for video

### ISSUE THREAD

**Issue by Petar-tech** [mudoo/quill-resize-module#3]
When i embed a video it doesn't seem to resize, on the images it works fine.

**Comment by mudoo** [comment]
You need to replace the default video blot.  https://github.com/mudoo/quill-resize-module/blob/master/demo/script.js#L22-L38

**Comment by kirqe** [comment]
@mudoo I'm getting an empty box that can be resized  with the following contents`<video class></video>` 

And after adding `PlaceholderRegister([VideoPlaceholder])` the following box

<img width="564" alt="Screenshot 2021-07-21 at 20 08 52" src="https://user-images.githubusercontent.com/5272402/126530560-ce0e1f7d-3811-4016-9bb3-616e76556080.png">

I have tried adding the video blot that you referenced 

Sorry for re-openning
